language: java

script: gradle dist

install:
  - echo sonatypeUsername=none >> gradle.properties
  - echo sonatypePassword=none >> gradle.properties

deploy:
  provider: releases
  api_key:
    secure: HhKwxJkqgmjrGs0W6ajR5VqQ4SKYmmTFBEZkc1VZbjBshkAvAQ5Uc58yj1hSgW1BYi6NwjaUC7ftW+1+Oh72p2TDUlT3LX0S1W3VaaHNybMGpFcC9JDLTqBEaMxMDiDZc8sH8vux+QoQiSRrwnvUH+/ld6lLborxkX32UE2FVMM=
  file:
    - build/distributions/xmlcalabash1-asciidoctor-$TRAVIS_TAG.zip
  skip_cleanup: true
  on:
    tags: true
    all_branches: true
